# Generated by Django 5.0.1 on 2025-11-12 12:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('position', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('business_address', models.TextField(blank=True)),
                ('nature_of_business', models.CharField(blank=True, max_length=255)),
                ('business_activities', models.TextField(blank=True)),
                ('industry', models.CharField(blank=True, max_length=255)),
                ('products_services', models.TextField(blank=True)),
                ('target_market', models.CharField(blank=True, max_length=255)),
                ('years_operation', models.CharField(max_length=100)),
                ('business_structure', models.CharField(max_length=100)),
                ('employees', models.CharField(max_length=100)),
                ('locations', models.TextField()),
                ('short_term_goals', models.TextField()),
                ('long_term_goals', models.TextField()),
                ('challenges', models.TextField()),
                ('services_seeking', models.TextField()),
                ('additional_info', models.TextField()),
                ('company_size', models.CharField(blank=True, max_length=50)),
                ('annual_revenue', models.CharField(blank=True, max_length=50)),
                ('preferred_contact_method', models.CharField(blank=True, max_length=50)),
                ('urgency_level', models.CharField(blank=True, max_length=50)),
                ('budget_range', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_contacted', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_intent_id', models.CharField(max_length=255, unique=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='gbp', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='api.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
