import { motion } from 'framer-motion';
import { Link } from 'react-router-dom';

export const Careers = () => {
  return (
    <div className="pt-20 min-h-screen bg-gray-50 dark:bg-navy-950">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="text-center mb-12"
        >
          <h1 className="text-4xl md:text-5xl font-bold text-gray-900 dark:text-white mb-4">
            Careers at Brince Solutions
          </h1>
          <p className="text-xl text-gray-600 dark:text-gray-400">
            Join our team and help shape the future of business solutions
          </p>
        </motion.div>

        {/* Job Posting */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.2 }}
          className="bg-white dark:bg-navy-900 rounded-2xl shadow-lg p-8 md:p-12 mb-8"
        >
          <div className="mb-8">
            <h2 className="text-3xl font-bold text-gray-900 dark:text-white mb-2">
              Marketing and Sales Manager
            </h2>
            <div className="flex flex-wrap gap-4 text-gray-600 dark:text-gray-400 mb-6">
              <span className="flex items-center">
                <span className="mr-2">📍</span>
                Location: London
              </span>
              <span className="flex items-center">
                <span className="mr-2">💼</span>
                Employment Type: Full-time
              </span>
            </div>
          </div>

          <div className="prose dark:prose-invert max-w-none">
            <section className="mb-8">
              <h3 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">About the Role</h3>
              <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
                We are seeking a Marketing and Sales Manager to lead our efforts across the full customer journey—from awareness and lead generation, through to closing deals and driving ongoing revenue growth.
              </p>
              <p className="text-gray-700 dark:text-gray-300 leading-relaxed mt-4">
                You will be responsible for building and executing marketing campaigns, managing the sales pipeline, and aligning both functions so that marketing activities directly support sales targets.
              </p>
            </section>

            <section className="mb-8">
              <h3 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">Key Responsibilities</h3>
              
              <div className="space-y-6">
                <div>
                  <h4 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">1. Strategy & Planning</h4>
                  <ul className="list-disc list-inside space-y-2 text-gray-700 dark:text-gray-300 ml-4">
                    <li>Develop and own the integrated marketing and sales strategy aligned with company revenue goals.</li>
                    <li>Define target markets, customer segments, and value propositions.</li>
                    <li>Set monthly, quarterly, and annual targets for leads, opportunities, and revenue.</li>
                    <li>Create and manage the marketing and sales budget, ensuring strong ROI.</li>
                  </ul>
                </div>

                <div>
                  <h4 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">2. Marketing Management</h4>
                  <ul className="list-disc list-inside space-y-2 text-gray-700 dark:text-gray-300 ml-4">
                    <li>Plan and run multi-channel campaigns (email, social media, paid ads, events, content, partnerships).</li>
                    <li>Oversee content creation (blogs, case studies, landing pages, sales collateral, newsletters).</li>
                    <li>Manage the company website and ensure it is optimised for SEO and conversion.</li>
                    <li>Build and manage the marketing funnel from awareness to MQLs (Marketing Qualified Leads).</li>
                    <li>Analyse campaign performance and optimise for lead quality and cost per lead.</li>
                  </ul>
                </div>

                <div>
                  <h4 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">3. Sales Management</h4>
                  <ul className="list-disc list-inside space-y-2 text-gray-700 dark:text-gray-300 ml-4">
                    <li>Own and manage the sales pipeline from initial enquiry to closing.</li>
                    <li>Respond to, qualify, and follow up on leads generated by marketing and outbound efforts.</li>
                    <li>Conduct product/service presentations, demos, and consultations with prospects.</li>
                    <li>Prepare and present quotes, proposals, and contracts.</li>
                    <li>Negotiate terms and close deals to meet or exceed sales targets.</li>
                    <li>Maintain accurate CRM records for leads, opportunities, and accounts.</li>
                  </ul>
                </div>

                <div>
                  <h4 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">4. Alignment of Marketing & Sales</h4>
                  <ul className="list-disc list-inside space-y-2 text-gray-700 dark:text-gray-300 ml-4">
                    <li>Ensure smooth handover processes from marketing to sales (clear MQL/SQL definitions).</li>
                    <li>Provide feedback to marketing based on lead quality, objections, and market insights.</li>
                    <li>Work with leadership to refine positioning, messaging, and packages based on customer feedback.</li>
                    <li>Coordinate campaigns and promotions to support specific sales goals (e.g., product launches, seasonal offers).</li>
                  </ul>
                </div>

                <div>
                  <h4 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">5. Customer & Market Insights</h4>
                  <ul className="list-disc list-inside space-y-2 text-gray-700 dark:text-gray-300 ml-4">
                    <li>Conduct and review market, competitor, and customer research.</li>
                    <li>Maintain a deep understanding of customer needs, pain points, and buying behaviour.</li>
                    <li>Use insights to shape new offers, campaigns, and sales approaches.</li>
                    <li>Build and maintain strong relationships with key customers and partners.</li>
                  </ul>
                </div>

                <div>
                  <h4 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">6. Reporting & Analytics</h4>
                  <p className="text-gray-700 dark:text-gray-300 mb-2">Track and report on KPIs across marketing and sales, such as:</p>
                  <ul className="list-disc list-inside space-y-2 text-gray-700 dark:text-gray-300 ml-4">
                    <li>Number of leads, MQLs, SQLs</li>
                    <li>Conversion rates at each funnel stage</li>
                    <li>Revenue, average deal size, sales cycle length</li>
                    <li>Campaign performance (CPL, ROAS, etc.)</li>
                  </ul>
                  <p className="text-gray-700 dark:text-gray-300 mt-4">
                    Prepare regular performance reports and recommendations for improvement to management.
                  </p>
                </div>
              </div>
            </section>

            <section className="mb-8">
              <h3 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">Requirements</h3>
              
              <div className="mb-6">
                <h4 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">Must-Have</h4>
                <ul className="list-disc list-inside space-y-2 text-gray-700 dark:text-gray-300 ml-4">
                  <li>1+ years experience in marketing, sales, or a combined commercial role, with at least 1 year in a managerial or lead position.</li>
                  <li>Proven track record of meeting or exceeding sales targets.</li>
                  <li>Experience planning and executing digital marketing campaigns (email, social, paid, content, SEO).</li>
                  <li>Strong experience using CRM systems (e.g., HubSpot, Salesforce, Zoho) and marketing tools (e.g., email platforms, analytics).</li>
                  <li>Excellent communication, negotiation, and presentation skills.</li>
                  <li>Strong analytical skills and comfort working with KPIs and data.</li>
                  <li>Ability to manage multiple priorities and work in a fast-paced environment.</li>
                </ul>
              </div>

              <div>
                <h4 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">Nice-to-Have</h4>
                <ul className="list-disc list-inside space-y-2 text-gray-700 dark:text-gray-300 ml-4">
                  <li>Experience in B2B services or professional services.</li>
                  <li>Experience managing small teams or external agencies/freelancers.</li>
                  <li>Familiarity with marketing automation and lead scoring.</li>
                  <li>Basic understanding of design tools (e.g., Canva, Figma) for simple assets.</li>
                </ul>
              </div>
            </section>

            <section className="mb-8">
              <h3 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">Key Competencies</h3>
              <ul className="list-disc list-inside space-y-2 text-gray-700 dark:text-gray-300 ml-4">
                <li>Commercial mindset focused on revenue and profitability.</li>
                <li>Strategic thinker with a hands-on approach.</li>
                <li>Strong relationship-building skills, both internally and with clients.</li>
                <li>High level of ownership, accountability, and initiative.</li>
                <li>Adaptable and comfortable with change and experimentation.</li>
              </ul>
            </section>

            <div className="mt-12 pt-8 border-t border-gray-200 dark:border-gray-700">
              <Link
                to="/contact"
                className="inline-block px-8 py-4 bg-primary-500 text-white rounded-xl font-semibold hover:bg-primary-600 transition-all shadow-lg hover:shadow-xl"
              >
                Apply Now
              </Link>
            </div>
          </div>
        </motion.div>

        {/* Additional Info */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.4 }}
          className="bg-primary-50 dark:bg-primary-900/20 rounded-2xl p-8 text-center"
        >
          <h3 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">
            Don't see a role that fits?
          </h3>
          <p className="text-gray-700 dark:text-gray-300 mb-6">
            We're always looking for talented individuals to join our team. Send us your CV and we'll keep you in mind for future opportunities.
          </p>
          <Link
            to="/contact"
            className="inline-block px-6 py-3 bg-primary-500 text-white rounded-xl font-semibold hover:bg-primary-600 transition-all"
          >
            Send Your CV
          </Link>
        </motion.div>
      </div>
    </div>
  );
};

